import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { stripTypeScriptTypes } from 'node:module';
void test('article publishing excludes drafts and strips active HTML', async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'hubplc-article-test-'));
  assert.equal(path.dirname(temp), os.tmpdir(), 'Unexpected test directory');
  assert.ok(
    path.basename(temp).startsWith('hubplc-article-test-'),
    'Unexpected test path',
  );
  const script = fileURLToPath(
    new URL('../scripts/prepare-articles.mjs', import.meta.url),
  );
  try {
    await fs.mkdir(path.join(temp, 'content/articles'), { recursive: true });
    await fs.mkdir(path.join(temp, 'lib'));
    await fs.writeFile(
      path.join(temp, 'content/hidden-articles.json'),
      '["hidden"]',
    );
    const meta =
      '---\ntitle: 測試筆記\ndescription: 測試摘要\ndate: 2026-09-06\nauthor: 測試\ndraft: ';
    await fs.writeFile(
      path.join(temp, 'content/articles/draft.md'),
      meta + 'true\n---\n不應發佈',
    );
    await fs.writeFile(
      path.join(temp, 'content/articles/hidden.md'),
      meta + 'false\n---\n暫時下架內容',
    );
    await fs.mkdir(path.join(temp, 'app/articles/(posts)/hidden'), {
      recursive: true,
    });
    await fs.writeFile(
      path.join(temp, 'app/articles/(posts)/hidden/page.tsx'),
      '// Generated by prepare-articles; old route',
    );
    await fs.writeFile(
      path.join(temp, 'content/articles/published.md'),
      meta +
        'false\n---\n## 正文\n<script>alert(1)</script>\n[連結](javascript:alert)\n[待整理](https://hubplc.com/articles/hidden?x=1#part)',
    );
    execFileSync(process.execPath, [script], { cwd: temp });
    const data = JSON.parse(
      await fs.readFile(path.join(temp, 'lib/articles.generated.json'), 'utf8'),
    );
    assert.equal(data.length, 1);
    assert.equal(data[0].slug, 'published');
    assert.doesNotMatch(data[0].html, /href="[^"]*articles\/hidden/);
    await assert.rejects(
      fs.access(path.join(temp, 'app/articles/(posts)/hidden/page.tsx')),
    );
    assert.match(
      await fs.readFile(path.join(temp, 'content/articles/hidden.md'), 'utf8'),
      /暫時下架內容/,
    );
    assert.match(data[0].html, /<h2 id="section-1">正文<\/h2>/);
    assert.deepEqual(data[0].toc, [
      { id: 'section-1', title: '正文', level: 2 },
    ]);
    const index = JSON.parse(
      await fs.readFile(
        path.join(temp, 'lib/article-index.generated.json'),
        'utf8',
      ),
    );
    assert.equal(index.length, 1);
    assert.equal(index[0].slug, 'published');
    assert.equal('html' in index[0], false);
    const fulltext = JSON.parse(
      await fs.readFile(path.join(temp, 'public/article-search.json'), 'utf8'),
    );
    assert.equal(Object.keys(fulltext).length, 1);
    assert.match(fulltext.published, /正文/);
    assert.doesNotMatch(fulltext.published, /alert|<script/);
    assert.doesNotMatch(data[0].html, /<script|javascript:/);
    const page = await fs.readFile(
      path.join(temp, 'app/articles/(posts)/published/page.tsx'),
      'utf8',
    );
    const metadataModule = page.slice(
      page.indexOf('const article'),
      page.indexOf('export default'),
    );
    const { metadata } = await import(
      'data:text/javascript;base64,' +
        Buffer.from(stripTypeScriptTypes(metadataModule)).toString('base64')
    );
    assert.equal(
      metadata.alternates.canonical,
      'https://hubplc.com/articles/published',
    );
    await fs.writeFile(
      path.join(temp, 'content/articles/published.md'),
      meta + 'true\n---\n已撤回',
    );
    execFileSync(process.execPath, [script], { cwd: temp });
    assert.deepEqual(
      JSON.parse(
        await fs.readFile(
          path.join(temp, 'lib/articles.generated.json'),
          'utf8',
        ),
      ),
      [],
    );
    assert.deepEqual(
      JSON.parse(
        await fs.readFile(
          path.join(temp, 'public/article-search.json'),
          'utf8',
        ),
      ),
      {},
    );
    await assert.rejects(
      fs.access(path.join(temp, 'app/articles/(posts)/published/page.tsx')),
    );
  } finally {
    await fs.rm(temp, { recursive: true, force: true });
  }
});
