'use client';
import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {analogScale,convertBase,modbusAddress} from '@/lib/calculators';
function Field({label,value,change,suffix}:{label:string;value:string;change:(v:string)=>void;suffix?:string}){return <label className="field"><span>{label}</span><div><input value={value} onChange={e=>change(e.target.value)}/>{suffix&&<span>{suffix}</span>}</div></label>}
function calc<T,>(fn:()=>T):{data?:T;error?:string}{try{return {data:fn()}}catch(e){return {error:(e as Error).message}}}
const fmt=(n:number)=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:4}).format(n);
export default function Workbench(){
 const [tab,setTab]=useState('analog');
 const [current,setCurrent]=useState('12'),[low,setLow]=useState('0'),[high,setHigh]=useState('100');
 const [decimal,setDecimal]=useState('255'),[binary,setBinary]=useState('11111111'),[hex,setHex]=useState('FF');
 const [base,setBase]=useState(10),[raw,setRaw]=useState('255'),[address,setAddress]=useState('40001');
 const analog=calc(()=>analogScale(current,low,high)),converted=calc(()=>convertBase(raw,base)),modbus=calc(()=>modbusAddress(address));
 function update(v:string,b:number){setRaw(v);setBase(b);if(b===10)setDecimal(v);if(b===2)setBinary(v);if(b===16)setHex(v);const result=calc(()=>convertBase(v,b));if(result.data){setDecimal(result.data.decimal);setBinary(result.data.binary);setHex(result.data.hex)}}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'calculate_analog_signal',description:'計算 4–20 mA 工程值並更新工具輸入。',inputSchema:{type:'object',properties:{current:{type:'number'},low:{type:'number'},high:{type:'number'}},required:['current','low','high'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const data=input as Record<string,unknown>;if(!data||['current','low','high'].some(key=>typeof data[key]!=='number'))throw new Error('需要 current、low、high 數字');const result=analogScale(String(data.current),String(data.low),String(data.high));flushSync(()=>{setTab('analog');setCurrent(String(data.current));setLow(String(data.low));setHigh(String(data.high))});return result}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 return <section id="tools" className="workbench"><div className="section-heading"><span className="eyebrow">01 / 實用工具</span><span className="muted">在瀏覽器內計算</span></div><Tabs value={tab} onValueChange={value=>setTab(String(value))}><TabsList className="tool-tabs"><TabsTrigger value="analog">01 <span>4–20 mA 換算</span></TabsTrigger><TabsTrigger value="base">02 <span>進位轉換</span></TabsTrigger><TabsTrigger value="modbus">03 <span>Modbus 位址</span></TabsTrigger></TabsList>
 <TabsContent value="analog"><div className="tool-grid"><div className="inputs"><p className="eyebrow">ANALOG SIGNAL</p><h2>類比訊號換算</h2><p className="muted">把 4–20 mA 電流訊號轉成溫度、壓力或液位等工程值。</p><Field label="輸入電流" value={current} change={setCurrent} suffix="mA"/><div className="two-fields"><Field label="量程下限（4 mA）" value={low} change={setLow}/><Field label="量程上限（20 mA）" value={high} change={setHigh}/></div><button className="reset" onClick={()=>{setCurrent('12');setLow('0');setHigh('100')}}>↺ 重設範例</button></div><div className="result" aria-live="polite" aria-atomic="true"><span className="eyebrow">換算結果 / ENGINEERING VALUE</span>{analog.data?<><div className="big-number">{fmt(analog.data.value)}</div><p>工程值 <span className="result-tag">{fmt(analog.data.percent)}% 滿量程</span></p><div className="meter" role="img" aria-label={'量程百分比 '+fmt(analog.data.percent)+'%'}><div style={{width:Math.max(0,Math.min(100,analog.data.percent))+'%'}}/></div><div className="scale"><span>4 mA / {low}</span><span>20 mA / {high}</span></div>{analog.data.outside&&<p className="alert">電流超出 4–20 mA，結果為線性外推值。</p>}<div className="formula">{low} + ({current} − 4) ÷ 16 × ({high} − {low})</div></>:<p className="alert">{analog.error}</p>}</div></div><div className="tool-foot"><span>使用說明</span><p>適用於線性訊號。工程值單位與量程相同；若模組提供原始數位值，請先依模組規格換算成 mA。</p></div></TabsContent>
 <TabsContent value="base"><div className="tool-grid"><div className="inputs"><p className="eyebrow">NUMBER SYSTEM</p><h2>進位轉換</h2><p className="muted">編輯任一欄位，以最後編輯的數字計算右側結果。</p><Field label="十進位 DEC" value={decimal} change={v=>update(v,10)}/><Field label="十六進位 HEX（不含 0x）" value={hex} change={v=>update(v,16)}/><Field label="二進位 BIN（不含 0b）" value={binary} change={v=>update(v,2)}/></div><div className="result" aria-live="polite"><span className="eyebrow">換算結果 / UNSIGNED 32-BIT</span>{converted.data?<dl className="result-list"><dt>DEC · 十進位</dt><dd>{converted.data.decimal}</dd><dt>HEX · 十六進位</dt><dd>0x{converted.data.hex}</dd><dt>BIN · 二進位</dt><dd className="binary">{converted.data.binary}</dd></dl>:<p className="alert">{converted.error}</p>}</div></div><div className="tool-foot"><span>使用說明</span><p>支援 32 位元無號整數。不進行負數二補數、浮點數 IEEE 754 或位元組順序轉換。</p></div></TabsContent>
 <TabsContent value="modbus"><div className="tool-grid"><div className="inputs"><p className="eyebrow">MODBUS / HOLDING REGISTER</p><h2>保持暫存器位址</h2><p className="muted">將傳統五位數 4xxxx 參考編號換算成協定中的零起算位址。</p><Field label="保持暫存器參考編號" value={address} change={setAddress}/><p className="muted">例如 40001 → 0；40101 → 100。</p></div><div className="result" aria-live="polite"><span className="eyebrow">協定位址 / ZERO-BASED</span>{modbus.data?<><div className="big-number">{modbus.data.offset}</div><p>十進位偏移量</p><div className="formula">HEX 0x{modbus.data.hex}<br/>讀取功能碼 03</div></>:<p className="alert">{modbus.error}</p>}</div></div><div className="tool-foot"><span>使用說明</span><p>裝置手冊可能直接提供零起算位址或使用其他編號慣例，不能一律減 40001。請核對裝置手冊與主站設定。<a href="https://www.modbus.org/file/secure/modbusprotocolspecification.pdf" target="_blank" rel="noreferrer">Modbus 協定參考 ↗</a></p></div></TabsContent>
 </Tabs></section>
}

