export const conversionTools = [
  {
    slug: 'stopwatch',
    name: '線上碼錶',
    category: '單位',
    code: '00:00',
    description:
      '開始、暫停與單圈計時，支援全螢幕、快捷鍵、低功耗模式與分享連結。',
    keywords: '碼錶 碼表 秒錶 秒表 計時器 單圈 分段 stopwatch timer ECO',
    example: '第一圈累計 10 秒，第二圈累計 25 秒，第二圈的單圈時間為 15 秒。',
  },
  {
    slug: 'world-clock',
    name: '世界時間・台北時鐘',
    category: '單位',
    code: 'UTC+08',
    description: '以台灣台北為預設的即時世界時鐘，搜尋城市、國家／地區與時差。',
    keywords:
      '時間 時鐘 台灣 台北 世界 國家 時區 夏令時間 world clock Taipei Taiwan UTC',
    example: '台北 16:00 時，UTC 為 08:00；跨城市日期與時差會隨夏令時間更新。',
  },
  {
    slug: 'timestamp-converter',
    name: 'Unix 時間戳轉換',
    category: '單位',
    code: 'UNIX ↔ 時間',
    description: 'Unix 秒／毫秒與台北日期時間雙向轉換，顯示目前時間戳。',
    keywords: '時間戳 Unix timestamp 秒 毫秒 台北 台灣 日期 轉換',
    example: 'Unix 1767196800 秒對應台北 2026-01-01 00:00:00。',
  },
  {
    slug: 'date-calculator',
    name: '日期計算器',
    category: '單位',
    code: '日期 ± 天',
    description: '計算兩日期相差天數或指定天數前後的日期，今天以台北時間判定。',
    keywords: '日期 計算 天數 相差 幾天 台北 台灣 date 日曆 閏年',
    example: '2024-02-28 加 2 天為 2024-03-01；日期差以日曆天計算。',
  },
  {
    slug: 'length-converter',
    name: '長度單位換算',
    category: '單位',
    code: 'm ↔ ft',
    description: '公制、英制與海里長度換算，支援毫米、公尺、英尺及英里。',
    keywords: '長度 公里 公尺 米 英吋 英尺 英里 海里 yard mile',
    example: '1 inch = 25.4 mm；1 ft = 0.3048 m。',
  },
  {
    slug: 'temperature-converter',
    name: '溫度單位換算',
    category: '單位',
    code: '°C ↔ °F',
    description: '攝氏、華氏、克耳文、蘭氏與列氏五種溫標換算。',
    keywords: '溫度 攝氏 華氏 克氏 蘭氏 列氏 Kelvin Rankine Reaumur',
    example: '0 °C = 32 °F = 273.15 K。',
  },
  {
    slug: 'mass-converter',
    name: '重量／質量單位換算',
    category: '單位',
    code: 'kg ↔ lb',
    description: '毫克、公克、公斤、公噸、磅與盎司的質量換算。',
    keywords: '重量 質量 公斤 公克 磅 盎司 噸 lb oz',
    example: '1 lb = 0.45359237 kg。',
  },
  {
    slug: 'area-converter',
    name: '面積單位換算',
    category: '單位',
    code: 'm² ↔ ft²',
    description: '平方公尺、平方公分、公頃與平方英尺等面積換算。',
    keywords: '面積 平方 公頃 平方英尺 m2 ha',
    example: '1 ha = 10000 m²。',
  },
  {
    slug: 'volume-converter',
    name: '體積單位換算',
    category: '單位',
    code: 'L ↔ gal',
    description: '毫升、公升、立方公尺與美制／英制加侖換算。',
    keywords: '體積 容積 公升 毫升 立方 米 加侖 gallon',
    example: '1 美制 gallon = 3.785411784 L。',
  },
  {
    slug: 'pressure-converter',
    name: '壓力單位換算',
    category: '單位',
    code: 'bar ↔ psi',
    description: 'Pa、kPa、MPa、bar、psi、標準大氣壓及水柱壓力換算。',
    keywords: '壓力 大氣壓 水柱 bar psi kPa MPa kgf',
    example: '1 bar = 100 kPa。',
  },
  {
    slug: 'power-converter',
    name: '功率單位換算',
    category: '單位',
    code: 'W ↔ hp',
    description: '瓦特、千瓦、兆瓦與機械／公制馬力換算。',
    keywords: '功率 瓦特 千瓦 兆瓦 毫瓦 馬力 hp PS',
    example: '1 kW = 1000 W。機械馬力與公制馬力採不同定義。',
  },
  {
    slug: 'time-converter',
    name: '時間單位換算',
    category: '單位',
    code: 's ↔ h',
    description: '微秒、毫秒、秒、分鐘、小時與日的時間換算。',
    keywords: '時間 秒 毫秒 微秒 分鐘 小時 日 day',
    example: '1 h = 60 min = 3600 s。',
  },
  {
    slug: 'angle-converter',
    name: '角度換算',
    category: '單位',
    code: '° ↔ rad',
    description: '度、弧度、百分度、圈、角分與角秒互換。',
    keywords: '角度 弧度 圈 圓 角分 角秒 rad deg grad',
    example: '180° = π rad = 0.5 圈。',
  },
  {
    slug: 'capacitance-converter',
    name: '電容單位換算',
    category: '單位',
    code: 'µF ↔ pF',
    description: '法拉、毫法、微法、奈法與皮法的電容量換算。',
    keywords: '電容 法拉 毫法 微法 奈法 皮法 F uF nF pF',
    example: '1 µF = 1000 nF = 1000000 pF。',
  },
  {
    slug: 'speed-converter',
    name: '速度單位換算',
    category: '單位',
    code: 'm/s ↔ km/h',
    description: '公尺每秒、公里每小時、英尺每秒、英里每小時與節換算。',
    keywords: '速度 公里 米 秒 時速 mph knot 節 馬赫',
    example: '1 m/s = 3.6 km/h。',
  },
  {
    slug: 'storage-converter',
    name: '儲存容量單位換算',
    category: '單位',
    code: 'GB ↔ GiB',
    description: 'bit、byte、十進位 kB／GB 與二進位 KiB／GiB 換算。',
    keywords:
      '儲存 容量 位元 位元組 硬碟 記憶體 bit byte KB MB GB TB KiB MiB GiB',
    example: '1 GB = 1000000000 bytes；1 GiB = 1073741824 bytes。',
  },
  {
    slug: 'rmb-uppercase',
    name: '新台幣數字轉大寫',
    category: '編碼',
    code: '123 → 壹',
    description: '新台幣金額轉繁體中文大寫，精確處理圓、角、分與零位。',
    keywords:
      '新台幣 新臺幣 台幣 臺幣 金額 大寫 小寫 財務 中文 數字 TWD NTD 支票',
    example: '1001.05 → 新臺幣壹仟零壹圓零伍分。',
  },
  {
    slug: 'text-case',
    name: '英文大小寫轉換',
    category: '編碼',
    code: 'Aa ↔ aA',
    description: '英文大寫、小寫、標題首字母、句首與大小寫反轉。',
    keywords: '英文 字母 大小寫 轉換 uppercase lowercase title sentence',
    example: 'Hello PLC → HELLO PLC 或 hello plc。',
  },
  {
    slug: 'currency-converter',
    name: '匯率換算器',
    category: '單位',
    code: 'USD ↔ TWD',
    description: '新台幣、美元、人民幣等 20 種貨幣換算，顯示參考匯率日期。',
    keywords:
      '匯率 貨幣 外幣 新台幣 美元 人民幣 日圓 歐元 exchange TWD USD CNY',
    example: '手動匯率 1 USD = 32 TWD 時，100 USD = 3200 TWD；此為示範值。',
  },
] as const;
export const conversionExamples = Object.fromEntries(
  conversionTools.map((tool) => [tool.slug, tool.example]),
) as Record<(typeof conversionTools)[number]['slug'], string>;
