// Source: https://github.com/eggert/tz/blob/main/zone.tab (public domain), retrieved 2026-09-07.
// Country-specific table intentionally retains separate entries for countries sharing rules.
export const worldZones = [
  {
    country: 'UTC',
    countryName: '世界標準時間',
    zone: 'UTC',
    city: 'UTC',
  },
  {
    country: 'AD',
    countryName: '安道爾',
    zone: 'Europe/Andorra',
    city: 'Andorra',
  },
  {
    country: 'AE',
    countryName: '阿拉伯聯合大公國',
    zone: 'Asia/Dubai',
    city: '杜拜',
  },
  {
    country: 'AF',
    countryName: '阿富汗',
    zone: 'Asia/Kabul',
    city: 'Kabul',
  },
  {
    country: 'AG',
    countryName: '安地卡及巴布達',
    zone: 'America/Antigua',
    city: 'Antigua',
  },
  {
    country: 'AI',
    countryName: '安奎拉',
    zone: 'America/Anguilla',
    city: 'Anguilla',
  },
  {
    country: 'AL',
    countryName: '阿爾巴尼亞',
    zone: 'Europe/Tirane',
    city: 'Tirane',
  },
  {
    country: 'AM',
    countryName: '亞美尼亞',
    zone: 'Asia/Yerevan',
    city: 'Yerevan',
  },
  {
    country: 'AO',
    countryName: '安哥拉',
    zone: 'Africa/Luanda',
    city: 'Luanda',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/McMurdo',
    city: 'McMurdo',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Casey',
    city: 'Casey',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Davis',
    city: 'Davis',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/DumontDUrville',
    city: 'DumontDUrville',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Mawson',
    city: 'Mawson',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Palmer',
    city: 'Palmer',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Rothera',
    city: 'Rothera',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Syowa',
    city: 'Syowa',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Troll',
    city: 'Troll',
  },
  {
    country: 'AQ',
    countryName: '南極洲',
    zone: 'Antarctica/Vostok',
    city: 'Vostok',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Buenos_Aires',
    city: '布宜諾斯艾利斯',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Cordoba',
    city: 'Cordoba',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Salta',
    city: 'Salta',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Jujuy',
    city: 'Jujuy',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Tucuman',
    city: 'Tucuman',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Catamarca',
    city: 'Catamarca',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/La_Rioja',
    city: 'La Rioja',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/San_Juan',
    city: 'San Juan',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Mendoza',
    city: 'Mendoza',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/San_Luis',
    city: 'San Luis',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Rio_Gallegos',
    city: 'Rio Gallegos',
  },
  {
    country: 'AR',
    countryName: '阿根廷',
    zone: 'America/Argentina/Ushuaia',
    city: 'Ushuaia',
  },
  {
    country: 'AS',
    countryName: '美屬薩摩亞',
    zone: 'Pacific/Pago_Pago',
    city: 'Pago Pago',
  },
  {
    country: 'AT',
    countryName: '奧地利',
    zone: 'Europe/Vienna',
    city: '維也納',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Lord_Howe',
    city: 'Lord Howe',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Antarctica/Macquarie',
    city: 'Macquarie',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Hobart',
    city: 'Hobart',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Melbourne',
    city: '墨爾本',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Sydney',
    city: '雪梨',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Broken_Hill',
    city: 'Broken Hill',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Brisbane',
    city: 'Brisbane',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Lindeman',
    city: 'Lindeman',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Adelaide',
    city: '阿德雷德',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Darwin',
    city: 'Darwin',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Perth',
    city: '伯斯',
  },
  {
    country: 'AU',
    countryName: '澳洲',
    zone: 'Australia/Eucla',
    city: 'Eucla',
  },
  {
    country: 'AW',
    countryName: '荷屬阿魯巴',
    zone: 'America/Aruba',
    city: 'Aruba',
  },
  {
    country: 'AX',
    countryName: '奧蘭群島',
    zone: 'Europe/Mariehamn',
    city: 'Mariehamn',
  },
  {
    country: 'AZ',
    countryName: '亞塞拜然',
    zone: 'Asia/Baku',
    city: 'Baku',
  },
  {
    country: 'BA',
    countryName: '波士尼亞與赫塞哥維納',
    zone: 'Europe/Sarajevo',
    city: 'Sarajevo',
  },
  {
    country: 'BB',
    countryName: '巴貝多',
    zone: 'America/Barbados',
    city: 'Barbados',
  },
  {
    country: 'BD',
    countryName: '孟加拉',
    zone: 'Asia/Dhaka',
    city: '達卡',
  },
  {
    country: 'BE',
    countryName: '比利時',
    zone: 'Europe/Brussels',
    city: '布魯塞爾',
  },
  {
    country: 'BF',
    countryName: '布吉納法索',
    zone: 'Africa/Ouagadougou',
    city: 'Ouagadougou',
  },
  {
    country: 'BG',
    countryName: '保加利亞',
    zone: 'Europe/Sofia',
    city: 'Sofia',
  },
  {
    country: 'BH',
    countryName: '巴林',
    zone: 'Asia/Bahrain',
    city: 'Bahrain',
  },
  {
    country: 'BI',
    countryName: '蒲隆地',
    zone: 'Africa/Bujumbura',
    city: 'Bujumbura',
  },
  {
    country: 'BJ',
    countryName: '貝南',
    zone: 'Africa/Porto-Novo',
    city: 'Porto-Novo',
  },
  {
    country: 'BL',
    countryName: '聖巴瑟米',
    zone: 'America/St_Barthelemy',
    city: 'St Barthelemy',
  },
  {
    country: 'BM',
    countryName: '百慕達',
    zone: 'Atlantic/Bermuda',
    city: 'Bermuda',
  },
  {
    country: 'BN',
    countryName: '汶萊',
    zone: 'Asia/Brunei',
    city: 'Brunei',
  },
  {
    country: 'BO',
    countryName: '玻利維亞',
    zone: 'America/La_Paz',
    city: 'La Paz',
  },
  {
    country: 'BQ',
    countryName: '荷蘭加勒比區',
    zone: 'America/Kralendijk',
    city: 'Kralendijk',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Noronha',
    city: 'Noronha',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Belem',
    city: 'Belem',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Fortaleza',
    city: 'Fortaleza',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Recife',
    city: 'Recife',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Araguaina',
    city: 'Araguaina',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Maceio',
    city: 'Maceio',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Bahia',
    city: 'Bahia',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Sao_Paulo',
    city: '聖保羅',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Campo_Grande',
    city: 'Campo Grande',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Cuiaba',
    city: 'Cuiaba',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Santarem',
    city: 'Santarem',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Porto_Velho',
    city: 'Porto Velho',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Boa_Vista',
    city: 'Boa Vista',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Manaus',
    city: 'Manaus',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Eirunepe',
    city: 'Eirunepe',
  },
  {
    country: 'BR',
    countryName: '巴西',
    zone: 'America/Rio_Branco',
    city: 'Rio Branco',
  },
  {
    country: 'BS',
    countryName: '巴哈馬',
    zone: 'America/Nassau',
    city: 'Nassau',
  },
  {
    country: 'BT',
    countryName: '不丹',
    zone: 'Asia/Thimphu',
    city: 'Thimphu',
  },
  {
    country: 'BW',
    countryName: '波札那',
    zone: 'Africa/Gaborone',
    city: 'Gaborone',
  },
  {
    country: 'BY',
    countryName: '白俄羅斯',
    zone: 'Europe/Minsk',
    city: 'Minsk',
  },
  {
    country: 'BZ',
    countryName: '貝里斯',
    zone: 'America/Belize',
    city: 'Belize',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/St_Johns',
    city: 'St Johns',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Halifax',
    city: 'Halifax',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Glace_Bay',
    city: 'Glace Bay',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Moncton',
    city: 'Moncton',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Goose_Bay',
    city: 'Goose Bay',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Blanc-Sablon',
    city: 'Blanc-Sablon',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Toronto',
    city: '多倫多',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Iqaluit',
    city: 'Iqaluit',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Atikokan',
    city: 'Atikokan',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Winnipeg',
    city: 'Winnipeg',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Resolute',
    city: 'Resolute',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Rankin_Inlet',
    city: 'Rankin Inlet',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Regina',
    city: 'Regina',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Swift_Current',
    city: 'Swift Current',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Edmonton',
    city: 'Edmonton',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Cambridge_Bay',
    city: 'Cambridge Bay',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Inuvik',
    city: 'Inuvik',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Vancouver',
    city: '溫哥華',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Brit_Columbia/Golden',
    city: 'Golden',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Creston',
    city: 'Creston',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Dawson_Creek',
    city: 'Dawson Creek',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Fort_Nelson',
    city: 'Fort Nelson',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Whitehorse',
    city: 'Whitehorse',
  },
  {
    country: 'CA',
    countryName: '加拿大',
    zone: 'America/Dawson',
    city: 'Dawson',
  },
  {
    country: 'CC',
    countryName: '科克斯（基靈）群島',
    zone: 'Indian/Cocos',
    city: 'Cocos',
  },
  {
    country: 'CD',
    countryName: '剛果（金夏沙）',
    zone: 'Africa/Kinshasa',
    city: 'Kinshasa',
  },
  {
    country: 'CD',
    countryName: '剛果（金夏沙）',
    zone: 'Africa/Lubumbashi',
    city: 'Lubumbashi',
  },
  {
    country: 'CF',
    countryName: '中非共和國',
    zone: 'Africa/Bangui',
    city: 'Bangui',
  },
  {
    country: 'CG',
    countryName: '剛果（布拉薩）',
    zone: 'Africa/Brazzaville',
    city: 'Brazzaville',
  },
  {
    country: 'CH',
    countryName: '瑞士',
    zone: 'Europe/Zurich',
    city: '蘇黎世',
  },
  {
    country: 'CI',
    countryName: '象牙海岸',
    zone: 'Africa/Abidjan',
    city: 'Abidjan',
  },
  {
    country: 'CK',
    countryName: '庫克群島',
    zone: 'Pacific/Rarotonga',
    city: 'Rarotonga',
  },
  {
    country: 'CL',
    countryName: '智利',
    zone: 'America/Santiago',
    city: '聖地牙哥',
  },
  {
    country: 'CL',
    countryName: '智利',
    zone: 'America/Coyhaique',
    city: 'Coyhaique',
  },
  {
    country: 'CL',
    countryName: '智利',
    zone: 'America/Punta_Arenas',
    city: 'Punta Arenas',
  },
  {
    country: 'CL',
    countryName: '智利',
    zone: 'Pacific/Easter',
    city: 'Easter',
  },
  {
    country: 'CM',
    countryName: '喀麥隆',
    zone: 'Africa/Douala',
    city: 'Douala',
  },
  {
    country: 'CN',
    countryName: '中國',
    zone: 'Asia/Shanghai',
    city: '上海',
  },
  {
    country: 'CN',
    countryName: '中國',
    zone: 'Asia/Urumqi',
    city: 'Urumqi',
  },
  {
    country: 'CO',
    countryName: '哥倫比亞',
    zone: 'America/Bogota',
    city: '波哥大',
  },
  {
    country: 'CR',
    countryName: '哥斯大黎加',
    zone: 'America/Costa_Rica',
    city: 'Costa Rica',
  },
  {
    country: 'CU',
    countryName: '古巴',
    zone: 'America/Havana',
    city: '哈瓦那',
  },
  {
    country: 'CV',
    countryName: '維德角',
    zone: 'Atlantic/Cape_Verde',
    city: 'Cape Verde',
  },
  {
    country: 'CW',
    countryName: '庫拉索',
    zone: 'America/Curacao',
    city: 'Curacao',
  },
  {
    country: 'CX',
    countryName: '聖誕島',
    zone: 'Indian/Christmas',
    city: 'Christmas',
  },
  {
    country: 'CY',
    countryName: '賽普勒斯',
    zone: 'Asia/Nicosia',
    city: 'Nicosia',
  },
  {
    country: 'CY',
    countryName: '賽普勒斯',
    zone: 'Asia/Famagusta',
    city: 'Famagusta',
  },
  {
    country: 'CZ',
    countryName: '捷克',
    zone: 'Europe/Prague',
    city: '布拉格',
  },
  {
    country: 'DE',
    countryName: '德國',
    zone: 'Europe/Berlin',
    city: '柏林',
  },
  {
    country: 'DE',
    countryName: '德國',
    zone: 'Europe/Busingen',
    city: 'Busingen',
  },
  {
    country: 'DJ',
    countryName: '吉布地',
    zone: 'Africa/Djibouti',
    city: 'Djibouti',
  },
  {
    country: 'DK',
    countryName: '丹麥',
    zone: 'Europe/Copenhagen',
    city: '哥本哈根',
  },
  {
    country: 'DM',
    countryName: '多米尼克',
    zone: 'America/Dominica',
    city: 'Dominica',
  },
  {
    country: 'DO',
    countryName: '多明尼加共和國',
    zone: 'America/Santo_Domingo',
    city: 'Santo Domingo',
  },
  {
    country: 'DZ',
    countryName: '阿爾及利亞',
    zone: 'Africa/Algiers',
    city: 'Algiers',
  },
  {
    country: 'EC',
    countryName: '厄瓜多',
    zone: 'America/Guayaquil',
    city: 'Guayaquil',
  },
  {
    country: 'EC',
    countryName: '厄瓜多',
    zone: 'Pacific/Galapagos',
    city: 'Galapagos',
  },
  {
    country: 'EE',
    countryName: '愛沙尼亞',
    zone: 'Europe/Tallinn',
    city: 'Tallinn',
  },
  {
    country: 'EG',
    countryName: '埃及',
    zone: 'Africa/Cairo',
    city: '開羅',
  },
  {
    country: 'EH',
    countryName: '西撒哈拉',
    zone: 'Africa/El_Aaiun',
    city: 'El Aaiun',
  },
  {
    country: 'ER',
    countryName: '厄利垂亞',
    zone: 'Africa/Asmara',
    city: 'Asmara',
  },
  {
    country: 'ES',
    countryName: '西班牙',
    zone: 'Europe/Madrid',
    city: '馬德里',
  },
  {
    country: 'ES',
    countryName: '西班牙',
    zone: 'Africa/Ceuta',
    city: 'Ceuta',
  },
  {
    country: 'ES',
    countryName: '西班牙',
    zone: 'Atlantic/Canary',
    city: 'Canary',
  },
  {
    country: 'ET',
    countryName: '衣索比亞',
    zone: 'Africa/Addis_Ababa',
    city: 'Addis Ababa',
  },
  {
    country: 'FI',
    countryName: '芬蘭',
    zone: 'Europe/Helsinki',
    city: '赫爾辛基',
  },
  {
    country: 'FJ',
    countryName: '斐濟',
    zone: 'Pacific/Fiji',
    city: 'Fiji',
  },
  {
    country: 'FK',
    countryName: '福克蘭群島',
    zone: 'Atlantic/Stanley',
    city: 'Stanley',
  },
  {
    country: 'FM',
    countryName: '密克羅尼西亞',
    zone: 'Pacific/Chuuk',
    city: 'Chuuk',
  },
  {
    country: 'FM',
    countryName: '密克羅尼西亞',
    zone: 'Pacific/Pohnpei',
    city: 'Pohnpei',
  },
  {
    country: 'FM',
    countryName: '密克羅尼西亞',
    zone: 'Pacific/Kosrae',
    city: 'Kosrae',
  },
  {
    country: 'FO',
    countryName: '法羅群島',
    zone: 'Atlantic/Faroe',
    city: 'Faroe',
  },
  {
    country: 'FR',
    countryName: '法國',
    zone: 'Europe/Paris',
    city: '巴黎',
  },
  {
    country: 'GA',
    countryName: '加彭',
    zone: 'Africa/Libreville',
    city: 'Libreville',
  },
  {
    country: 'GB',
    countryName: '英國',
    zone: 'Europe/London',
    city: '倫敦',
  },
  {
    country: 'GD',
    countryName: '格瑞那達',
    zone: 'America/Grenada',
    city: 'Grenada',
  },
  {
    country: 'GE',
    countryName: '喬治亞',
    zone: 'Asia/Tbilisi',
    city: 'Tbilisi',
  },
  {
    country: 'GF',
    countryName: '法屬圭亞那',
    zone: 'America/Cayenne',
    city: 'Cayenne',
  },
  {
    country: 'GG',
    countryName: '根息',
    zone: 'Europe/Guernsey',
    city: 'Guernsey',
  },
  {
    country: 'GH',
    countryName: '迦納',
    zone: 'Africa/Accra',
    city: 'Accra',
  },
  {
    country: 'GI',
    countryName: '直布羅陀',
    zone: 'Europe/Gibraltar',
    city: 'Gibraltar',
  },
  {
    country: 'GL',
    countryName: '格陵蘭',
    zone: 'America/Nuuk',
    city: 'Nuuk',
  },
  {
    country: 'GL',
    countryName: '格陵蘭',
    zone: 'America/Danmarkshavn',
    city: 'Danmarkshavn',
  },
  {
    country: 'GL',
    countryName: '格陵蘭',
    zone: 'America/Scoresbysund',
    city: 'Scoresbysund',
  },
  {
    country: 'GL',
    countryName: '格陵蘭',
    zone: 'America/Thule',
    city: 'Thule',
  },
  {
    country: 'GM',
    countryName: '甘比亞',
    zone: 'Africa/Banjul',
    city: 'Banjul',
  },
  {
    country: 'GN',
    countryName: '幾內亞',
    zone: 'Africa/Conakry',
    city: 'Conakry',
  },
  {
    country: 'GP',
    countryName: '瓜地洛普',
    zone: 'America/Guadeloupe',
    city: 'Guadeloupe',
  },
  {
    country: 'GQ',
    countryName: '赤道幾內亞',
    zone: 'Africa/Malabo',
    city: 'Malabo',
  },
  {
    country: 'GR',
    countryName: '希臘',
    zone: 'Europe/Athens',
    city: '雅典',
  },
  {
    country: 'GS',
    countryName: '南喬治亞與南三明治群島',
    zone: 'Atlantic/South_Georgia',
    city: 'South Georgia',
  },
  {
    country: 'GT',
    countryName: '瓜地馬拉',
    zone: 'America/Guatemala',
    city: 'Guatemala',
  },
  {
    country: 'GU',
    countryName: '關島',
    zone: 'Pacific/Guam',
    city: 'Guam',
  },
  {
    country: 'GW',
    countryName: '幾內亞比索',
    zone: 'Africa/Bissau',
    city: 'Bissau',
  },
  {
    country: 'GY',
    countryName: '蓋亞那',
    zone: 'America/Guyana',
    city: 'Guyana',
  },
  {
    country: 'HK',
    countryName: '中國香港特別行政區',
    zone: 'Asia/Hong_Kong',
    city: '香港',
  },
  {
    country: 'HN',
    countryName: '宏都拉斯',
    zone: 'America/Tegucigalpa',
    city: 'Tegucigalpa',
  },
  {
    country: 'HR',
    countryName: '克羅埃西亞',
    zone: 'Europe/Zagreb',
    city: 'Zagreb',
  },
  {
    country: 'HT',
    countryName: '海地',
    zone: 'America/Port-au-Prince',
    city: 'Port-au-Prince',
  },
  {
    country: 'HU',
    countryName: '匈牙利',
    zone: 'Europe/Budapest',
    city: 'Budapest',
  },
  {
    country: 'ID',
    countryName: '印尼',
    zone: 'Asia/Jakarta',
    city: '雅加達',
  },
  {
    country: 'ID',
    countryName: '印尼',
    zone: 'Asia/Pontianak',
    city: 'Pontianak',
  },
  {
    country: 'ID',
    countryName: '印尼',
    zone: 'Asia/Makassar',
    city: 'Makassar',
  },
  {
    country: 'ID',
    countryName: '印尼',
    zone: 'Asia/Jayapura',
    city: 'Jayapura',
  },
  {
    country: 'IE',
    countryName: '愛爾蘭',
    zone: 'Europe/Dublin',
    city: '都柏林',
  },
  {
    country: 'IL',
    countryName: '以色列',
    zone: 'Asia/Jerusalem',
    city: '耶路撒冷',
  },
  {
    country: 'IM',
    countryName: '曼島',
    zone: 'Europe/Isle_of_Man',
    city: 'Isle of Man',
  },
  {
    country: 'IN',
    countryName: '印度',
    zone: 'Asia/Kolkata',
    city: '加爾各答',
  },
  {
    country: 'IO',
    countryName: '英屬印度洋領地',
    zone: 'Indian/Chagos',
    city: 'Chagos',
  },
  {
    country: 'IQ',
    countryName: '伊拉克',
    zone: 'Asia/Baghdad',
    city: '巴格達',
  },
  {
    country: 'IR',
    countryName: '伊朗',
    zone: 'Asia/Tehran',
    city: '德黑蘭',
  },
  {
    country: 'IS',
    countryName: '冰島',
    zone: 'Atlantic/Reykjavik',
    city: '雷克雅維克',
  },
  {
    country: 'IT',
    countryName: '義大利',
    zone: 'Europe/Rome',
    city: '羅馬',
  },
  {
    country: 'JE',
    countryName: '澤西島',
    zone: 'Europe/Jersey',
    city: 'Jersey',
  },
  {
    country: 'JM',
    countryName: '牙買加',
    zone: 'America/Jamaica',
    city: 'Jamaica',
  },
  {
    country: 'JO',
    countryName: '約旦',
    zone: 'Asia/Amman',
    city: 'Amman',
  },
  {
    country: 'JP',
    countryName: '日本',
    zone: 'Asia/Tokyo',
    city: '東京',
  },
  {
    country: 'KE',
    countryName: '肯亞',
    zone: 'Africa/Nairobi',
    city: '奈洛比',
  },
  {
    country: 'KG',
    countryName: '吉爾吉斯',
    zone: 'Asia/Bishkek',
    city: 'Bishkek',
  },
  {
    country: 'KH',
    countryName: '柬埔寨',
    zone: 'Asia/Phnom_Penh',
    city: '金邊',
  },
  {
    country: 'KI',
    countryName: '吉里巴斯',
    zone: 'Pacific/Tarawa',
    city: 'Tarawa',
  },
  {
    country: 'KI',
    countryName: '吉里巴斯',
    zone: 'Pacific/Kanton',
    city: 'Kanton',
  },
  {
    country: 'KI',
    countryName: '吉里巴斯',
    zone: 'Pacific/Kiritimati',
    city: 'Kiritimati',
  },
  {
    country: 'KM',
    countryName: '葛摩',
    zone: 'Indian/Comoro',
    city: 'Comoro',
  },
  {
    country: 'KN',
    countryName: '聖克里斯多福及尼維斯',
    zone: 'America/St_Kitts',
    city: 'St Kitts',
  },
  {
    country: 'KP',
    countryName: '北韓',
    zone: 'Asia/Pyongyang',
    city: '平壤',
  },
  {
    country: 'KR',
    countryName: '南韓',
    zone: 'Asia/Seoul',
    city: '首爾',
  },
  {
    country: 'KW',
    countryName: '科威特',
    zone: 'Asia/Kuwait',
    city: 'Kuwait',
  },
  {
    country: 'KY',
    countryName: '開曼群島',
    zone: 'America/Cayman',
    city: 'Cayman',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Almaty',
    city: 'Almaty',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Qyzylorda',
    city: 'Qyzylorda',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Qostanay',
    city: 'Qostanay',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Aqtobe',
    city: 'Aqtobe',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Aqtau',
    city: 'Aqtau',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Atyrau',
    city: 'Atyrau',
  },
  {
    country: 'KZ',
    countryName: '哈薩克',
    zone: 'Asia/Oral',
    city: 'Oral',
  },
  {
    country: 'LA',
    countryName: '寮國',
    zone: 'Asia/Vientiane',
    city: '永珍',
  },
  {
    country: 'LB',
    countryName: '黎巴嫩',
    zone: 'Asia/Beirut',
    city: 'Beirut',
  },
  {
    country: 'LC',
    countryName: '聖露西亞',
    zone: 'America/St_Lucia',
    city: 'St Lucia',
  },
  {
    country: 'LI',
    countryName: '列支敦斯登',
    zone: 'Europe/Vaduz',
    city: 'Vaduz',
  },
  {
    country: 'LK',
    countryName: '斯里蘭卡',
    zone: 'Asia/Colombo',
    city: 'Colombo',
  },
  {
    country: 'LR',
    countryName: '賴比瑞亞',
    zone: 'Africa/Monrovia',
    city: 'Monrovia',
  },
  {
    country: 'LS',
    countryName: '賴索托',
    zone: 'Africa/Maseru',
    city: 'Maseru',
  },
  {
    country: 'LT',
    countryName: '立陶宛',
    zone: 'Europe/Vilnius',
    city: 'Vilnius',
  },
  {
    country: 'LU',
    countryName: '盧森堡',
    zone: 'Europe/Luxembourg',
    city: 'Luxembourg',
  },
  {
    country: 'LV',
    countryName: '拉脫維亞',
    zone: 'Europe/Riga',
    city: 'Riga',
  },
  {
    country: 'LY',
    countryName: '利比亞',
    zone: 'Africa/Tripoli',
    city: 'Tripoli',
  },
  {
    country: 'MA',
    countryName: '摩洛哥',
    zone: 'Africa/Casablanca',
    city: 'Casablanca',
  },
  {
    country: 'MC',
    countryName: '摩納哥',
    zone: 'Europe/Monaco',
    city: 'Monaco',
  },
  {
    country: 'MD',
    countryName: '摩爾多瓦',
    zone: 'Europe/Chisinau',
    city: 'Chisinau',
  },
  {
    country: 'ME',
    countryName: '蒙特內哥羅',
    zone: 'Europe/Podgorica',
    city: 'Podgorica',
  },
  {
    country: 'MF',
    countryName: '法屬聖馬丁',
    zone: 'America/Marigot',
    city: 'Marigot',
  },
  {
    country: 'MG',
    countryName: '馬達加斯加',
    zone: 'Indian/Antananarivo',
    city: 'Antananarivo',
  },
  {
    country: 'MH',
    countryName: '馬紹爾群島',
    zone: 'Pacific/Majuro',
    city: 'Majuro',
  },
  {
    country: 'MH',
    countryName: '馬紹爾群島',
    zone: 'Pacific/Kwajalein',
    city: 'Kwajalein',
  },
  {
    country: 'MK',
    countryName: '北馬其頓',
    zone: 'Europe/Skopje',
    city: 'Skopje',
  },
  {
    country: 'ML',
    countryName: '馬利',
    zone: 'Africa/Bamako',
    city: 'Bamako',
  },
  {
    country: 'MM',
    countryName: '緬甸',
    zone: 'Asia/Yangon',
    city: '仰光',
  },
  {
    country: 'MN',
    countryName: '蒙古',
    zone: 'Asia/Ulaanbaatar',
    city: '烏蘭巴托',
  },
  {
    country: 'MN',
    countryName: '蒙古',
    zone: 'Asia/Hovd',
    city: 'Hovd',
  },
  {
    country: 'MO',
    countryName: '中國澳門特別行政區',
    zone: 'Asia/Macau',
    city: '澳門',
  },
  {
    country: 'MP',
    countryName: '北馬利安納群島',
    zone: 'Pacific/Saipan',
    city: 'Saipan',
  },
  {
    country: 'MQ',
    countryName: '馬丁尼克',
    zone: 'America/Martinique',
    city: 'Martinique',
  },
  {
    country: 'MR',
    countryName: '茅利塔尼亞',
    zone: 'Africa/Nouakchott',
    city: 'Nouakchott',
  },
  {
    country: 'MS',
    countryName: '蒙哲臘',
    zone: 'America/Montserrat',
    city: 'Montserrat',
  },
  {
    country: 'MT',
    countryName: '馬爾他',
    zone: 'Europe/Malta',
    city: 'Malta',
  },
  {
    country: 'MU',
    countryName: '模里西斯',
    zone: 'Indian/Mauritius',
    city: 'Mauritius',
  },
  {
    country: 'MV',
    countryName: '馬爾地夫',
    zone: 'Indian/Maldives',
    city: 'Maldives',
  },
  {
    country: 'MW',
    countryName: '馬拉威',
    zone: 'Africa/Blantyre',
    city: 'Blantyre',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Mexico_City',
    city: '墨西哥城',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Cancun',
    city: 'Cancun',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Merida',
    city: 'Merida',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Monterrey',
    city: 'Monterrey',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Matamoros',
    city: 'Matamoros',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Chihuahua',
    city: 'Chihuahua',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Ciudad_Juarez',
    city: 'Ciudad Juarez',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Ojinaga',
    city: 'Ojinaga',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Mazatlan',
    city: 'Mazatlan',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Bahia_Banderas',
    city: 'Bahia Banderas',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Hermosillo',
    city: 'Hermosillo',
  },
  {
    country: 'MX',
    countryName: '墨西哥',
    zone: 'America/Tijuana',
    city: 'Tijuana',
  },
  {
    country: 'MY',
    countryName: '馬來西亞',
    zone: 'Asia/Kuala_Lumpur',
    city: '吉隆坡',
  },
  {
    country: 'MY',
    countryName: '馬來西亞',
    zone: 'Asia/Kuching',
    city: 'Kuching',
  },
  {
    country: 'MZ',
    countryName: '莫三比克',
    zone: 'Africa/Maputo',
    city: 'Maputo',
  },
  {
    country: 'NA',
    countryName: '納米比亞',
    zone: 'Africa/Windhoek',
    city: 'Windhoek',
  },
  {
    country: 'NC',
    countryName: '新喀里多尼亞',
    zone: 'Pacific/Noumea',
    city: 'Noumea',
  },
  {
    country: 'NE',
    countryName: '尼日',
    zone: 'Africa/Niamey',
    city: 'Niamey',
  },
  {
    country: 'NF',
    countryName: '諾福克島',
    zone: 'Pacific/Norfolk',
    city: 'Norfolk',
  },
  {
    country: 'NG',
    countryName: '奈及利亞',
    zone: 'Africa/Lagos',
    city: '拉哥斯',
  },
  {
    country: 'NI',
    countryName: '尼加拉瓜',
    zone: 'America/Managua',
    city: 'Managua',
  },
  {
    country: 'NL',
    countryName: '荷蘭',
    zone: 'Europe/Amsterdam',
    city: '阿姆斯特丹',
  },
  {
    country: 'NO',
    countryName: '挪威',
    zone: 'Europe/Oslo',
    city: '奧斯陸',
  },
  {
    country: 'NP',
    countryName: '尼泊爾',
    zone: 'Asia/Kathmandu',
    city: '加德滿都',
  },
  {
    country: 'NR',
    countryName: '諾魯',
    zone: 'Pacific/Nauru',
    city: 'Nauru',
  },
  {
    country: 'NU',
    countryName: '紐埃島',
    zone: 'Pacific/Niue',
    city: 'Niue',
  },
  {
    country: 'NZ',
    countryName: '紐西蘭',
    zone: 'Pacific/Auckland',
    city: '奧克蘭',
  },
  {
    country: 'NZ',
    countryName: '紐西蘭',
    zone: 'Pacific/Chatham',
    city: 'Chatham',
  },
  {
    country: 'OM',
    countryName: '阿曼',
    zone: 'Asia/Muscat',
    city: 'Muscat',
  },
  {
    country: 'PA',
    countryName: '巴拿馬',
    zone: 'America/Panama',
    city: 'Panama',
  },
  {
    country: 'PE',
    countryName: '秘魯',
    zone: 'America/Lima',
    city: '利馬',
  },
  {
    country: 'PF',
    countryName: '法屬玻里尼西亞',
    zone: 'Pacific/Tahiti',
    city: 'Tahiti',
  },
  {
    country: 'PF',
    countryName: '法屬玻里尼西亞',
    zone: 'Pacific/Marquesas',
    city: 'Marquesas',
  },
  {
    country: 'PF',
    countryName: '法屬玻里尼西亞',
    zone: 'Pacific/Gambier',
    city: 'Gambier',
  },
  {
    country: 'PG',
    countryName: '巴布亞紐幾內亞',
    zone: 'Pacific/Port_Moresby',
    city: 'Port Moresby',
  },
  {
    country: 'PG',
    countryName: '巴布亞紐幾內亞',
    zone: 'Pacific/Bougainville',
    city: 'Bougainville',
  },
  {
    country: 'PH',
    countryName: '菲律賓',
    zone: 'Asia/Manila',
    city: '馬尼拉',
  },
  {
    country: 'PK',
    countryName: '巴基斯坦',
    zone: 'Asia/Karachi',
    city: '喀拉蚩',
  },
  {
    country: 'PL',
    countryName: '波蘭',
    zone: 'Europe/Warsaw',
    city: '華沙',
  },
  {
    country: 'PM',
    countryName: '聖皮埃與密克隆群島',
    zone: 'America/Miquelon',
    city: 'Miquelon',
  },
  {
    country: 'PN',
    countryName: '皮特肯群島',
    zone: 'Pacific/Pitcairn',
    city: 'Pitcairn',
  },
  {
    country: 'PR',
    countryName: '波多黎各',
    zone: 'America/Puerto_Rico',
    city: 'Puerto Rico',
  },
  {
    country: 'PS',
    countryName: '巴勒斯坦自治區',
    zone: 'Asia/Gaza',
    city: 'Gaza',
  },
  {
    country: 'PS',
    countryName: '巴勒斯坦自治區',
    zone: 'Asia/Hebron',
    city: 'Hebron',
  },
  {
    country: 'PT',
    countryName: '葡萄牙',
    zone: 'Europe/Lisbon',
    city: '里斯本',
  },
  {
    country: 'PT',
    countryName: '葡萄牙',
    zone: 'Atlantic/Madeira',
    city: 'Madeira',
  },
  {
    country: 'PT',
    countryName: '葡萄牙',
    zone: 'Atlantic/Azores',
    city: 'Azores',
  },
  {
    country: 'PW',
    countryName: '帛琉',
    zone: 'Pacific/Palau',
    city: 'Palau',
  },
  {
    country: 'PY',
    countryName: '巴拉圭',
    zone: 'America/Asuncion',
    city: 'Asuncion',
  },
  {
    country: 'QA',
    countryName: '卡達',
    zone: 'Asia/Qatar',
    city: 'Qatar',
  },
  {
    country: 'RE',
    countryName: '留尼旺',
    zone: 'Indian/Reunion',
    city: 'Reunion',
  },
  {
    country: 'RO',
    countryName: '羅馬尼亞',
    zone: 'Europe/Bucharest',
    city: 'Bucharest',
  },
  {
    country: 'RS',
    countryName: '塞爾維亞',
    zone: 'Europe/Belgrade',
    city: 'Belgrade',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Kaliningrad',
    city: 'Kaliningrad',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Moscow',
    city: '莫斯科',
  },
  {
    country: 'UA',
    countryName: '烏克蘭',
    zone: 'Europe/Simferopol',
    city: 'Simferopol',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Kirov',
    city: 'Kirov',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Volgograd',
    city: 'Volgograd',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Astrakhan',
    city: 'Astrakhan',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Saratov',
    city: 'Saratov',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Ulyanovsk',
    city: 'Ulyanovsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Europe/Samara',
    city: 'Samara',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Yekaterinburg',
    city: 'Yekaterinburg',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Omsk',
    city: 'Omsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Novosibirsk',
    city: 'Novosibirsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Barnaul',
    city: 'Barnaul',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Tomsk',
    city: 'Tomsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Novokuznetsk',
    city: 'Novokuznetsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Krasnoyarsk',
    city: 'Krasnoyarsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Irkutsk',
    city: 'Irkutsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Chita',
    city: 'Chita',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Yakutsk',
    city: 'Yakutsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Khandyga',
    city: 'Khandyga',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Vladivostok',
    city: 'Vladivostok',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Ust-Nera',
    city: 'Ust-Nera',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Magadan',
    city: 'Magadan',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Sakhalin',
    city: 'Sakhalin',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Srednekolymsk',
    city: 'Srednekolymsk',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Kamchatka',
    city: 'Kamchatka',
  },
  {
    country: 'RU',
    countryName: '俄羅斯',
    zone: 'Asia/Anadyr',
    city: 'Anadyr',
  },
  {
    country: 'RW',
    countryName: '盧安達',
    zone: 'Africa/Kigali',
    city: 'Kigali',
  },
  {
    country: 'SA',
    countryName: '沙烏地阿拉伯',
    zone: 'Asia/Riyadh',
    city: '利雅德',
  },
  {
    country: 'SB',
    countryName: '索羅門群島',
    zone: 'Pacific/Guadalcanal',
    city: 'Guadalcanal',
  },
  {
    country: 'SC',
    countryName: '塞席爾',
    zone: 'Indian/Mahe',
    city: 'Mahe',
  },
  {
    country: 'SD',
    countryName: '蘇丹',
    zone: 'Africa/Khartoum',
    city: 'Khartoum',
  },
  {
    country: 'SE',
    countryName: '瑞典',
    zone: 'Europe/Stockholm',
    city: '斯德哥爾摩',
  },
  {
    country: 'SG',
    countryName: '新加坡',
    zone: 'Asia/Singapore',
    city: '新加坡',
  },
  {
    country: 'SH',
    countryName: '聖赫勒拿島',
    zone: 'Atlantic/St_Helena',
    city: 'St Helena',
  },
  {
    country: 'SI',
    countryName: '斯洛維尼亞',
    zone: 'Europe/Ljubljana',
    city: 'Ljubljana',
  },
  {
    country: 'SJ',
    countryName: '挪威屬斯瓦巴及尖棉',
    zone: 'Arctic/Longyearbyen',
    city: 'Longyearbyen',
  },
  {
    country: 'SK',
    countryName: '斯洛伐克',
    zone: 'Europe/Bratislava',
    city: 'Bratislava',
  },
  {
    country: 'SL',
    countryName: '獅子山',
    zone: 'Africa/Freetown',
    city: 'Freetown',
  },
  {
    country: 'SM',
    countryName: '聖馬利諾',
    zone: 'Europe/San_Marino',
    city: 'San Marino',
  },
  {
    country: 'SN',
    countryName: '塞內加爾',
    zone: 'Africa/Dakar',
    city: 'Dakar',
  },
  {
    country: 'SO',
    countryName: '索馬利亞',
    zone: 'Africa/Mogadishu',
    city: 'Mogadishu',
  },
  {
    country: 'SR',
    countryName: '蘇利南',
    zone: 'America/Paramaribo',
    city: 'Paramaribo',
  },
  {
    country: 'SS',
    countryName: '南蘇丹',
    zone: 'Africa/Juba',
    city: 'Juba',
  },
  {
    country: 'ST',
    countryName: '聖多美普林西比',
    zone: 'Africa/Sao_Tome',
    city: 'Sao Tome',
  },
  {
    country: 'SV',
    countryName: '薩爾瓦多',
    zone: 'America/El_Salvador',
    city: 'El Salvador',
  },
  {
    country: 'SX',
    countryName: '荷屬聖馬丁',
    zone: 'America/Lower_Princes',
    city: 'Lower Princes',
  },
  {
    country: 'SY',
    countryName: '敘利亞',
    zone: 'Asia/Damascus',
    city: 'Damascus',
  },
  {
    country: 'SZ',
    countryName: '史瓦帝尼',
    zone: 'Africa/Mbabane',
    city: 'Mbabane',
  },
  {
    country: 'TC',
    countryName: '土克斯及開科斯群島',
    zone: 'America/Grand_Turk',
    city: 'Grand Turk',
  },
  {
    country: 'TD',
    countryName: '查德',
    zone: 'Africa/Ndjamena',
    city: 'Ndjamena',
  },
  {
    country: 'TF',
    countryName: '法屬南部屬地',
    zone: 'Indian/Kerguelen',
    city: 'Kerguelen',
  },
  {
    country: 'TG',
    countryName: '多哥',
    zone: 'Africa/Lome',
    city: 'Lome',
  },
  {
    country: 'TH',
    countryName: '泰國',
    zone: 'Asia/Bangkok',
    city: '曼谷',
  },
  {
    country: 'TJ',
    countryName: '塔吉克',
    zone: 'Asia/Dushanbe',
    city: 'Dushanbe',
  },
  {
    country: 'TK',
    countryName: '托克勞群島',
    zone: 'Pacific/Fakaofo',
    city: 'Fakaofo',
  },
  {
    country: 'TL',
    countryName: '東帝汶',
    zone: 'Asia/Dili',
    city: 'Dili',
  },
  {
    country: 'TM',
    countryName: '土庫曼',
    zone: 'Asia/Ashgabat',
    city: 'Ashgabat',
  },
  {
    country: 'TN',
    countryName: '突尼西亞',
    zone: 'Africa/Tunis',
    city: 'Tunis',
  },
  {
    country: 'TO',
    countryName: '東加',
    zone: 'Pacific/Tongatapu',
    city: 'Tongatapu',
  },
  {
    country: 'TR',
    countryName: '土耳其',
    zone: 'Europe/Istanbul',
    city: '伊斯坦堡',
  },
  {
    country: 'TT',
    countryName: '千里達及托巴哥',
    zone: 'America/Port_of_Spain',
    city: 'Port of Spain',
  },
  {
    country: 'TV',
    countryName: '吐瓦魯',
    zone: 'Pacific/Funafuti',
    city: 'Funafuti',
  },
  {
    country: 'TW',
    countryName: '台灣',
    zone: 'Asia/Taipei',
    city: '台北',
  },
  {
    country: 'TZ',
    countryName: '坦尚尼亞',
    zone: 'Africa/Dar_es_Salaam',
    city: 'Dar es Salaam',
  },
  {
    country: 'UA',
    countryName: '烏克蘭',
    zone: 'Europe/Kyiv',
    city: '基輔',
  },
  {
    country: 'UG',
    countryName: '烏干達',
    zone: 'Africa/Kampala',
    city: 'Kampala',
  },
  {
    country: 'UM',
    countryName: '美國本土外小島嶼',
    zone: 'Pacific/Midway',
    city: 'Midway',
  },
  {
    country: 'UM',
    countryName: '美國本土外小島嶼',
    zone: 'Pacific/Wake',
    city: 'Wake',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/New_York',
    city: '紐約',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Detroit',
    city: 'Detroit',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Kentucky/Louisville',
    city: 'Louisville',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Kentucky/Monticello',
    city: 'Monticello',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Indianapolis',
    city: 'Indianapolis',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Vincennes',
    city: 'Vincennes',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Winamac',
    city: 'Winamac',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Marengo',
    city: 'Marengo',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Petersburg',
    city: 'Petersburg',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Vevay',
    city: 'Vevay',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Chicago',
    city: '芝加哥',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Tell_City',
    city: 'Tell City',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Indiana/Knox',
    city: 'Knox',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Menominee',
    city: 'Menominee',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/North_Dakota/Center',
    city: 'Center',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/North_Dakota/New_Salem',
    city: 'New Salem',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/North_Dakota/Beulah',
    city: 'Beulah',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Denver',
    city: '丹佛',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Boise',
    city: 'Boise',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Phoenix',
    city: 'Phoenix',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Los_Angeles',
    city: '洛杉磯',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Anchorage',
    city: '安克拉治',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Juneau',
    city: 'Juneau',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Sitka',
    city: 'Sitka',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Metlakatla',
    city: 'Metlakatla',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Yakutat',
    city: 'Yakutat',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Nome',
    city: 'Nome',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'America/Adak',
    city: 'Adak',
  },
  {
    country: 'US',
    countryName: '美國',
    zone: 'Pacific/Honolulu',
    city: '檀香山',
  },
  {
    country: 'UY',
    countryName: '烏拉圭',
    zone: 'America/Montevideo',
    city: 'Montevideo',
  },
  {
    country: 'UZ',
    countryName: '烏茲別克',
    zone: 'Asia/Samarkand',
    city: 'Samarkand',
  },
  {
    country: 'UZ',
    countryName: '烏茲別克',
    zone: 'Asia/Tashkent',
    city: 'Tashkent',
  },
  {
    country: 'VA',
    countryName: '梵蒂岡',
    zone: 'Europe/Vatican',
    city: 'Vatican',
  },
  {
    country: 'VC',
    countryName: '聖文森及格瑞那丁',
    zone: 'America/St_Vincent',
    city: 'St Vincent',
  },
  {
    country: 'VE',
    countryName: '委內瑞拉',
    zone: 'America/Caracas',
    city: '卡拉卡斯',
  },
  {
    country: 'VG',
    countryName: '英屬維京群島',
    zone: 'America/Tortola',
    city: 'Tortola',
  },
  {
    country: 'VI',
    countryName: '美屬維京群島',
    zone: 'America/St_Thomas',
    city: 'St Thomas',
  },
  {
    country: 'VN',
    countryName: '越南',
    zone: 'Asia/Ho_Chi_Minh',
    city: '胡志明市',
  },
  {
    country: 'VU',
    countryName: '萬那杜',
    zone: 'Pacific/Efate',
    city: 'Efate',
  },
  {
    country: 'WF',
    countryName: '瓦利斯群島和富圖那群島',
    zone: 'Pacific/Wallis',
    city: 'Wallis',
  },
  {
    country: 'WS',
    countryName: '薩摩亞',
    zone: 'Pacific/Apia',
    city: 'Apia',
  },
  {
    country: 'YE',
    countryName: '葉門',
    zone: 'Asia/Aden',
    city: 'Aden',
  },
  {
    country: 'YT',
    countryName: '馬約特島',
    zone: 'Indian/Mayotte',
    city: 'Mayotte',
  },
  {
    country: 'ZA',
    countryName: '南非',
    zone: 'Africa/Johannesburg',
    city: '約翰尼斯堡',
  },
  {
    country: 'ZM',
    countryName: '尚比亞',
    zone: 'Africa/Lusaka',
    city: 'Lusaka',
  },
  {
    country: 'ZW',
    countryName: '辛巴威',
    zone: 'Africa/Harare',
    city: 'Harare',
  },
] as const;
